### ISSUE TITLE
KMD trading fee error

### ISSUE THREAD

**Issue by kelcie33** [KomodoPlatform/atomicdexweb_bugreport#17]
On the swap page, the KMD fee is shown to be 28368.00 for trading around 200 USD worth of BTC for 200 USD of KMD and also for $2 worth.

<img width="691" alt="Screen Shot 2022-06-05 at 12 35 24 PM" src="https://user-images.githubusercontent.com/10329007/172067508-91c3a204-9f3c-483d-ad8a-2e4dfd124468.png">

<img width="662" alt="Screen Shot 2022-06-05 at 12 35 18 PM" src="https://user-images.githubusercontent.com/10329007/172067515-f3bb986d-4a4c-4209-b06a-550634d9cf61.png">

MacBook Pro M1 Max 
OS Monterey:12.3.1 (21E258)
Browsers: CHROME DESKTOP Version 102.0.5005.61
and Safari Desktop Version 15.4 (17613.1.17.1.13)

**Comment by tonymorony** [comment]
Thank you for the issue opening! 

Actually 28368.00 there is not a fee but price in KMD per one BTC in fiat. I do agree that it might be confusing, we are reworking trading widgets and will consider this feedback during the design [ CC @polevin @yurii-khi ]
